import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  async redirects() {
    return [
      { source: "/about-us", destination: "/about", permanent: true },
      { source: "/about-us/", destination: "/about", permanent: true },
      { source: "/faqs", destination: "/faq", permanent: true },
      { source: "/faqs/", destination: "/faq", permanent: true },
      { source: "/team", destination: "/about", permanent: true },
      { source: "/team/", destination: "/about", permanent: true },
      { source: "/why-ai", destination: "/pricing#ai-visibility", permanent: true },
      { source: "/why-ai/", destination: "/pricing#ai-visibility", permanent: true },
      { source: "/zemfar-why-ai", destination: "/pricing#ai-visibility", permanent: true },
      { source: "/zemfar-why-ai-v2", destination: "/pricing#ai-visibility", permanent: true },
      { source: "/ai-voice-agents", destination: "/pricing#relay", permanent: true },
      { source: "/ai-voice-agents/", destination: "/pricing#relay", permanent: true },
      { source: "/reviews", destination: "/pricing#review-automation", permanent: true },
      { source: "/reviews/", destination: "/pricing#review-automation", permanent: true },
      { source: "/ai-visibility", destination: "/pricing#ai-visibility", permanent: true },
      { source: "/ai-visibility/", destination: "/pricing#ai-visibility", permanent: true },
      { source: "/relay", destination: "/pricing#relay", permanent: true },
      { source: "/relay/", destination: "/pricing#relay", permanent: true },
      { source: "/studio", destination: "/pricing#studio", permanent: true },
      { source: "/studio/", destination: "/pricing#studio", permanent: true },
      { source: "/rankings", destination: "/pricing#ai-visibility", permanent: true },
      { source: "/rankings/", destination: "/pricing#ai-visibility", permanent: true },
      { source: "/success-stories", destination: "/blog", permanent: true },
      { source: "/success-stories/", destination: "/blog", permanent: true },
      { source: "/blog/google-vs-chatgpt-where-buyers-land", destination: "/blog/why-chatgpt-recommends-by-name", permanent: true },
      { source: "/blog/google-vs-chatgpt-where-buyers-land/", destination: "/blog/why-chatgpt-recommends-by-name", permanent: true },
      { source: "/blog/what-chatgpt-sees-when-it-looks-at-your-business", destination: "/blog/why-chatgpt-recommends-by-name", permanent: true },
      { source: "/blog/what-chatgpt-sees-when-it-looks-at-your-business/", destination: "/blog/why-chatgpt-recommends-by-name", permanent: true },
      { source: "/ai-powered-services", destination: "/", permanent: true },
      { source: "/ai-powered-services/", destination: "/", permanent: true },
      { source: "/ai-powered-services-old", destination: "/", permanent: true },
      { source: "/ai-products-services", destination: "/", permanent: true },
      { source: "/ai-automations", destination: "/", permanent: true },
      { source: "/privacy-policy", destination: "/privacy", permanent: true },
      { source: "/privacy-policy/", destination: "/privacy", permanent: true },
      { source: "/terms-and-conditions", destination: "/terms", permanent: true },
      { source: "/terms-and-conditions/", destination: "/terms", permanent: true },
      { source: "/terms-and-disclosures", destination: "/terms", permanent: true },
      { source: "/terms-and-disclosures/", destination: "/terms", permanent: true },
      { source: "/review-boost", destination: "/pricing#review-automation", permanent: true },
      { source: "/review-boost/", destination: "/pricing#review-automation", permanent: true },
      { source: "/custom-solutions", destination: "/contact", permanent: true },
      { source: "/custom-solutions/", destination: "/contact", permanent: true },

      { source: "/:slug(zemfar-.*)", destination: "/", permanent: true },

      { source: "/service/:path*", destination: "/", permanent: true },
      { source: "/service_category/:path*", destination: "/", permanent: true },
      { source: "/product/:path*", destination: "/", permanent: true },
      { source: "/product-category/:path*", destination: "/", permanent: true },
      { source: "/product-tag/:path*", destination: "/", permanent: true },
      { source: "/portfolio/:path*", destination: "/", permanent: true },
      { source: "/portfolio_category/:path*", destination: "/", permanent: true },
      { source: "/category/:path*", destination: "/", permanent: true },
      { source: "/tag/:path*", destination: "/", permanent: true },
      { source: "/elementskit-content/:path*", destination: "/", permanent: true },
      { source: "/header/:path*", destination: "/", permanent: true },
    ];
  },
};

export default nextConfig;
